[package]
name = "ost-template"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = [
	"Katharina Tschirky"
]
license = "MIT"
description = "Template for OST students"
repository = "https://github.com/k-tsky/OST-typst-template"
categories = ["thesis"]
disciplines = ["computer-science"]


[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"